### ISSUE TITLE
where to implement debug_print() function?

### ISSUE THREAD

**Issue by schuub** [Phantom5522/NekoNeko-chan#3]
debug_print() function needs to be implemented in a useful way

currently it's in clawTest.py line 23 and maybe some other test files, but we should only have 1 instance of this function in our code

would it makes sense to move this to main.py? or make it part of the NekoNekoChan class?

**Comment by Phantom5522** [comment]
I would make a own file/class for standard functions!

**Comment by schuub** [comment]
done in 878dd7cf1453847aa2991db05a69664b3656d73f

import debug class from toolbox and use debug.print()
